/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as EventsIdIndexRouteImport } from './routes/events.$id.index'
import { Route as EventsIdStatsRouteImport } from './routes/events.$id.stats'
import { Route as EventsIdEditRouteImport } from './routes/events.$id.edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EventsRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const EventsIdIndexRoute = EventsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdStatsRoute = EventsIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdEditRoute = EventsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/events/': typeof EventsIndexRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/stats': typeof EventsIdStatsRoute
  '/events/$id/': typeof EventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/events/new': typeof EventsNewRoute
  '/events': typeof EventsIndexRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/stats': typeof EventsIdStatsRoute
  '/events/$id': typeof EventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/events/': typeof EventsIndexRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/stats': typeof EventsIdStatsRoute
  '/events/$id/': typeof EventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/login'
    | '/my-events'
    | '/profile'
    | '/events/$id'
    | '/events/new'
    | '/events/'
    | '/events/$id/edit'
    | '/events/$id/stats'
    | '/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/my-events'
    | '/profile'
    | '/events/new'
    | '/events'
    | '/events/$id/edit'
    | '/events/$id/stats'
    | '/events/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events'
    | '/login'
    | '/my-events'
    | '/profile'
    | '/events/$id'
    | '/events/new'
    | '/events/'
    | '/events/$id/edit'
    | '/events/$id/stats'
    | '/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/new': {
      id: '/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$id/': {
      id: '/events/$id/'
      path: '/'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof EventsIdIndexRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/stats': {
      id: '/events/$id/stats'
      path: '/stats'
      fullPath: '/events/$id/stats'
      preLoaderRoute: typeof EventsIdStatsRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/edit': {
      id: '/events/$id/edit'
      path: '/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof EventsIdEditRouteImport
      parentRoute: typeof EventsIdRoute
    }
  }
}

interface EventsIdRouteChildren {
  EventsIdEditRoute: typeof EventsIdEditRoute
  EventsIdStatsRoute: typeof EventsIdStatsRoute
  EventsIdIndexRoute: typeof EventsIdIndexRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdEditRoute: EventsIdEditRoute,
  EventsIdStatsRoute: EventsIdStatsRoute,
  EventsIdIndexRoute: EventsIdIndexRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRouteWithChildren
  EventsNewRoute: typeof EventsNewRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRouteWithChildren,
  EventsNewRoute: EventsNewRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
